### ISSUE TITLE
フロントの側作り

### ISSUE THREAD

**Issue by Sakauchi444** [Sakauchi444/argut_ai#6]
フロントの側作り。（イメージはLINEよりもキャラクター同士が会話している感じ。）

成果物
・勝敗予想画面
・議論画面
・最終勝敗画面
・上3つの画面を移動するときに挟む画面を考え、作成。（決まってないから考えるとこから）

あとなんかある？

**Comment by Taka1304** [comment]
優先度: 必須
- Topページ
- 議論(`/argutia`)
  - 議論するテーマ、使用AI設定
  - 勝敗予想画面
  - 議論画面
  - 最終勝敗画面
- 過去に行われた対戦を閲覧できるページ
  - 検索、一覧表示する画面(`/argutia/search`)
  - 詳細画面(`/argutia/[id]`)
    - ISRかな？

優先度: あったらいいよね
- AIの対戦成績(通算)が可視化されてるページ
  - 勝率の推移とか
- How to Playページ
- 利用規約
- プライバシーポリシー
